### ISSUE TITLE
As user, I want to download my todos so that I can store them safely

### ISSUE THREAD

**Issue by Nicola3341246** [Nicola3341246/zu-bbbearbeiten-stateless#17]
# Acceptance Criteria

|     Given      |       When        |          Then          |
| :------------: | :---------------: | :--------------------: |
| Opened Page | Press on save-button | The stuff downloads |

# Subtasks
- [x] Function converts Todos ti string
- [x] Interface for Api
- [x] Implement into html

# Further information
Try to keep your user stories as expressive as possible. The less subtasks and further information are necessary to understand it, the better. Ideally, you should be able to delete these two sections; but, of course, keep them if necessary.
